version: '3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: task_management_system
#      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - TaskManagementSystem

  app:
    build: .
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/task_management_system?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "9095:9090"
    networks:
      - TaskManagementSystem

networks:
  TaskManagementSystem:
